### ISSUE TITLE
Autoware Version

### ISSUE THREAD

**Issue by AOOOOOA** [Juanpalai/AirSim-ROS-Wrapper-for-Autoware#1]
Hi, May I ask for which version of Autoware the wrapper can be used? Since there are Autoware.ai, Autoware.auto, and the latest Autoware.universe. They use different ROS versions.
Thanks!

**Comment by Juanpalai** [comment]
Hi there! The wrapper has been tested and confirmed compatible with the following versions of Autoware and ROS:

- Autoware.AI version 1.11.1 using ROS Kinetic on Ubuntu 16.04.
- Autoware Universe version 2022.12 using ROS 2 Humble on Ubuntu 22.04.

Regarding Autoware.auto and other versions, the wrapper's compatibility hasn't been explicitly tested or verified.

If you have any more questions or if there's anything else I can assist you with, please feel free to ask!
